defaults:
  - base_config
  - _self_

train:
  batch_size: 6
  epochs: 15
  shuffle: True
  num_workers: 4

transform:
  
  fer2013:
    img_size: 48
    output_channels: 3
  
  jaffe:
    img_size: 256
    output_channels: 3

  ckplus:
    img_size: 128
    output_channels: 3